### PR TITLE
♻ (mixins) add new sass rem generator

### PR DESCRIPTION
**Pull request by borisdamevin**

### CODE REVIEW

**Comment by davejtoews** [comment]
Hi @borisdamevin, I'm not familiar with your sass-rem library. What is the advantage of using this one over the other one?

**Comment by borisdamevin** [comment]
This library is up to date with "Sass Module System" and when the old Sass system is removed from the next major version, you will already be up to date.

**Comment by davejtoews** [comment]
That sounds good. I'll take a closer look at this at a later date. Thanks for the PR.

**Comment by borisdamevin** [comment]
Hi @davejtoews 

Any news for this PR? :)

**Comment by davejtoews** [comment]
Hi @borisdamevin. I haven't had the downtime I would like to have to tie up loose ends and finally release a 1.0 version. Are you making use of our library, or just checking in on your PRs?

**Comment by davejtoews** [comment]
sass-rem has now been updated to use sass modules, so this PR is no longer necessary.

**Pull request closed without merging**
